"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require('2.0')
import gtk

class CellRendererText(gtk.CellRendererText):
	def __init__(self, column, model_index = None):
		gtk.CellRendererText.__init__(self)

		column.pack_start(self, True)
		column.add_attribute(self, "text", model_index)
