"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require("2.0")
import gtk
import util

class TreeView(gtk.TreeView):
	def __init__(self, k_tree = None):
		gtk.TreeView.__init__(self, util.TreeStoreBuilder.build(k_tree) if k_tree is not None else None)

	def set_model(self, k_tree):
		gtk.TreeView.set_model(self, util.TreeStoreBuilder.build(k_tree) if k_tree is not None else None)
