"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require('2.0')
import gtk

class CellRendererProgress(gtk.CellRendererProgress):
	def __init__(self, column, model_index, expand = False):
		gtk.CellRendererProgress.__init__(self)

		column.pack_start(self, expand)
		column.add_attribute(self, "value", model_index)
