"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require('2.0')
import gtk

class CellRendererPixbuf(gtk.CellRendererPixbuf):
	def __init__(self, column, stock_id = None, pixel_buffer = None, expand = False):
		gtk.CellRendererPixbuf.__init__(self)

		column.pack_start(self, expand)

		if stock_id is not None:
			column.add_attribute(self, "stock-id", stock_id)
		elif pixel_buffer is not None:
			column.add_attribute(self, "pixbuf", pixel_buffer)
