"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require("2.0")
import gtk
import util

class ListView(gtk.TreeView):
	def __init__(self, array = None):
		gtk.TreeView.__init__(self, util.ListStoreBuilder.build(array) if array is not None else None)

	def set_model(self, array):
		gtk.TreeView.set_model(self, util.ListStoreBuilder.build(array) if array is not None else None)
