"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require("2.0")
import gtk

class ListStoreBuilder:
	@staticmethod
	def build(array):
		arguments = []

		for value in array[0]:
			arguments.append(type(value))
		
		store = gtk.ListStore(*arguments)

		for item in array:
			store.append(item)

		return store
