"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import pygtk
pygtk.require("2.0")
import gtk

class TreeStoreBuilder:
	@staticmethod
	def build(k_tree):
		arguments = []

		for value in k_tree.get_value():
			arguments.append(type(value))
		
		store = gtk.TreeStore(*arguments)
		TreeStoreBuilder.__build_node(store, k_tree, None)

		return store

	@staticmethod
	def __build_node(store, k_tree_node, iter):
		node_iter = store.append(iter, k_tree_node.get_value())

		for child_node in k_tree_node.get_children():
			TreeStoreBuilder.__build_node(store, child_node, node_iter)
