"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class KTree:
	def __init__(self, value):
		self._value = value
		self._children = []
		self._parent = None

	def get_value(self):
		return self._value

	def get_children(self):
		return self._children

	def get_child(self, index):
		return self._children[index]

	def get_parent(self):
		return self._parent

	def add_child(self, child):
		self._children.append(child)
		child._parent = self
